In [2]:
import numpy as np


array = np.array(([1, 4, 19, 10, 5], [3, 9, 10, 8, 8]))

array_4 = np.copy(array)
print(array_4)

array_5 = array[:]
print(array_5)

print(id(array_4))
print(id(array_5))
print(id(array))

array_6 = array

print(id(array))
print(id(array_6))

[[ 1  4 19 10  5]
 [ 3  9 10  8  8]]
[[ 1  4 19 10  5]
 [ 3  9 10  8  8]]
124266480
124266840
124266800
124266800
124266800


In [15]:
array_7= np.array([5, 0, -2, 0.0], dtype=bool)
print(array_7)

[ True False  True False]


In [14]:
array = np.array([1, 0, 1, 1, 0, 1, 0, 0], dtype=bool)
array_2 = np.array([1, 1, 0, 0, 0, 1, 1, 0], dtype=bool)

array_3 = array | array_2
array_4 = array & array_2
print(array_3)
print(array_4)
print()
array_5 = np.logical_or(array, array_2)
array_6 = np.logical_and(array, array_2)
print(array_5)
print(array_6)

[ True  True  True  True False  True  True False]
[ True False False False False  True False False]

[ True  True  True  True False  True  True False]
[ True False False False False  True False False]


In [16]:
array_7= np.array([5, 0, -2, 0.0], dtype=bool)
all(array_7)

False

In [17]:
array_7= np.array([5, 0, -2, 0.0], dtype=bool)
any(array_7)

True

In [22]:
np.random.seed(0)
array = np.random.randint(0, 100, (5, 5))
print(array)

# Operadores
print(array < 50)
print(array == 88)

# Métodos
print(np.equal(array, 30))
print(np.less(array, 50))
print(np.count_nonzero(array))
print(np.sum(array < 50, axis=1)) # cuántos elementos menores a 50 en cada fila


[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]
 [81 37 25 77 72]]
[[ True  True False False False]
 [ True False  True  True False]
 [False False False  True False]
 [False  True False  True False]
 [False  True  True False False]]
[[False False False False False]
 [False False False False False]
 [False  True  True False False]
 [False False False False  True]
 [False False False False False]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[ True  True False False False]
 [ True False  True  True False]
 [False False False  True False]
 [False  True False  True False]
 [False  True  True False False]]
25
[2 3 1 2 2]


In [23]:
# Arreglo estructurado
name = ["Alice", "Bob", "Cathy", "Doug"]
age = [25, 35, 45, 55]
heigth = [1.55, 1.81, 1.67, 1.78]

data = np.zeros(4, dtype={'names': ('name', 'age', 'height'), 'formats': ('U10', 'i4', 'f8')})
data['name'] = name
data['age'] = age
data['height'] = heigth

print(data)

# Records: los labels pueden ser accedidos como si fueran atributos
data = np.rec.array([("Alice", 25, 1.55), ("Bob", 35, 1.81), ("Cathy", 45, 1.67), ("Doug", 55, 1.78)],
                   dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f8')])
print(data.name)
print(data.age)
print(data.height)

[('Alice', 25, 1.55) ('Bob', 35, 1.81) ('Cathy', 45, 1.67)
 ('Doug', 55, 1.78)]
['Alice' 'Bob' 'Cathy' 'Doug']
[25 35 45 55]
[1.55 1.81 1.67 1.78]
