In [2]:
import numpy as np
from scipy import stats


lista_numeros =  [100, 9, -5, -5, 6, 99, 200, 44, 21, 789, -10, -11, 21, 30]
arr_numeros = np.array(lista_numeros)
print(arr_numeros)

media = np.mean(arr_numeros)
print(media)

mediana = np.median(arr_numeros)
print(mediana)

moda = stats.mode(arr_numeros)
print(moda)

percentil = np.percentile(arr_numeros, 25)
print(percentil)

varianza = np.var(arr_numeros)
print(varianza)

desvio = np.std(arr_numeros)
print(desvio)


[100   9  -5  -5   6  99 200  44  21 789 -10 -11  21  30]
92.0
21.0
ModeResult(mode=array([-5]), count=array([2]))
-2.25
40566.57142857143
201.41144810703148


In [7]:
matriz = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(matriz)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.float64)  # indico el tipo de dato
print(array)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [4]:
array_unos = np.ones((3, 4), dtype=np.int64) #por defecto los toma como float
print(array_unos)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [6]:
array_zeros = np.zeros((5, 2), dtype=np.int64)
print(array_zeros)
array_empty = np.empty((5, 2))
print(array_empty)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
array_random = np.random.random((3, 2)) #crea entre 0 y 1
array_randomint = np.random.randint(1, 8, 6, dtype=np.int64) #entre 1 y 8 me saca 6 numeros
print(array_random)
print(array_randomint)

[[0.11128642 0.26418801]
 [0.04763018 0.04317049]
 [0.29577377 0.6700692 ]]
[2 5 5 7 5 4]


In [4]:
dieciocho = np.full((3,4),18)
print(dieciocho)

[[18 18 18 18]
 [18 18 18 18]
 [18 18 18 18]]


In [15]:
arreglo_arange = np.arange(0, 10, 3)
print(arreglo_arange)
arreglo_linespace = np.linspace(0, 10, 3)
print(arreglo_linespace)

[0 3 6 9]
[ 0.  5. 10.]


In [16]:
identidad=np.identity(5)
print(identidad)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
array = np.array([(1, 3, 5, 7), (9, 3, 4, 5), (1, 1, 1, 1)])

print(array.shape)  # dimensión
print(array.dtype)  # tipo de dato
print(array.size)  # cantidad de elementos del arreglo


(3, 4)
int32
12


In [21]:
array = np.array([(8, 9, 10, 7), (11, 12, 13, 9)])
print(array)
print()
array = array.reshape(4, 2)
print(array)

[[ 8  9 10  7]
 [11 12 13  9]]

[[ 8  9]
 [10  7]
 [11 12]
 [13  9]]


In [22]:
array = np.array([(8, 9, 10), (11, 12, 13)])
print(np.sqrt(array))
print(np.std(array))

array_2 = np.array([(7, 16, 1), (9, 12, 6)])
print(array + array_2)
print(array - array_2)

[[2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128]]
1.707825127659933
[[15 25 11]
 [20 24 19]]
[[ 1 -7  9]
 [ 2  0  7]]


In [23]:
array = np.array([(8, 7, 9), (10, 11, 4)])
array_2 = 1 + array
print(array_2)

[[ 9  8 10]
 [11 12  5]]
